[workspace]
members = [
    "crates/rssp-core",
    "crates/rssp",
    "crates/rssp-cli",
]
resolver = "3"

[workspace.package]
version = "0.4.110"

[workspace.dependencies]
rssp = { path = "crates/rssp", version = "0.4.110" }
rssp-core = { path = "crates/rssp-core", version = "0.4.110" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
debug = true
