[package]
name = "rssp-cli"
version.workspace = true
edition = "2024"
authors = ["Patrik Nilsson <perfecttaste@pm.me>"]
description = "Command-line tools for rssp."
repository = "https://github.com/pnn64/rssp"
license = "MIT"
keywords = ["stepmania", "simfile", "parser", "rust", "rssp"]

[dependencies]
png = "0.18.1"
rssp = { workspace = true }

[[bin]]
name = "rssp"
path = "src/main.rs"

[lints.clippy]
pedantic = "warn"

inline_always = "allow"
